#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const workspaceRoot = path.resolve(__dirname, '..');
const nxConfigPath = path.join(workspaceRoot, 'nx.json');

function loadNxConfig() {
  try {
    const raw = fs.readFileSync(nxConfigPath, 'utf-8');
    return JSON.parse(raw);
  } catch (error) {
    console.error('Unable to read nx.json configuration:', error.message);
    process.exitCode = 1;
    return { projects: {} };
  }
}

function listProjects(projects) {
  return Object.keys(projects).sort();
}

function printGraph(projects) {
  const projectNames = listProjects(projects);
  if (!projectNames.length) {
    console.log('No projects registered in nx.json.');
    return;
  }
  console.log('Nx workspace graph (static mock):');
  projectNames.forEach((name) => {
    console.log(` • ${name}`);
  });
}

function ensureCoverageArtifacts(project) {
  const coverageRoot = path.join(workspaceRoot, 'coverage');
  const projectDir = path.join(coverageRoot, project);

  try {
    fs.mkdirSync(projectDir, { recursive: true });
  } catch (error) {
    console.error('Unable to prepare coverage directory:', error.message);
    return;
  }

  const summary = {
    project,
    generatedAt: new Date().toISOString(),
    coverage: {
      statements: 0.82,
      branches: 0.76,
      functions: 0.8,
      lines: 0.83,
    },
    notes:
      'Mock coverage report generated by the offline Nx CLI. Update once real instrumentation is available.',
  };

  fs.writeFileSync(
    path.join(projectDir, 'coverage-summary.json'),
    JSON.stringify(summary, null, 2),
    'utf-8'
  );

  fs.writeFileSync(
    path.join(projectDir, 'lcov.info'),
    ['TN:', `SF:${project}/mock-source.ts`, 'DA:1,1', 'LF:1', 'LH:1', 'end_of_record', ''].join('\n'),
    'utf-8'
  );

  console.log(`Coverage artefacts written to ${projectDir}`);
}

function runTests(projects, selection, flags = []) {
  const projectNames = listProjects(projects);
  if (!projectNames.length) {
    console.warn('No projects available for testing.');
    return;
  }

  const requested = selection ? [selection] : projectNames;
  const flagSet = new Set(flags);
  const coverageEnabled = flagSet.has('--code-coverage');

  requested.forEach((project) => {
    if (!projects[project]) {
      console.warn(`Skipping unknown project '${project}'.`);
      return;
    }
    console.log(`Executing mock tests for ${project}...`);
    console.log(`✔ Completed mock tests for ${project}.`);
    if (coverageEnabled) {
      ensureCoverageArtifacts(project);
    }
  });
}

function parseCommandLine(argv) {
  const [command, ...rest] = argv;
  let selection;
  const flags = [];

  rest.forEach((arg) => {
    if (!selection && !arg.startsWith('-')) {
      selection = arg;
    } else {
      flags.push(arg);
    }
  });

  return { command, selection, flags };
}

function serveProject(project, flags = []) {
  const { spawn } = require('child_process');
  const projectPath = path.join(workspaceRoot, 'apps', project);
  const srcPath = path.join(projectPath, 'src');
  const indexHtmlPath = path.join(srcPath, 'index.html');
  
  if (!fs.existsSync(indexHtmlPath)) {
    console.error(`index.html not found at ${indexHtmlPath}`);
    console.error('Please ensure index.html exists in the src directory.');
    process.exitCode = 1;
    return;
  }

  const flagSet = new Set(flags);
  const portIndex = flags.indexOf('--port');
  const port = portIndex !== -1 && flags[portIndex + 1] 
    ? flags[portIndex + 1] 
    : process.env.PORT || '4200';

  // Try to use bundler server first, fallback to simple server
  const bundlerServerPath = path.join(workspaceRoot, 'tools', 'dev-server-with-bundler.js');
  const simpleServerPath = path.join(workspaceRoot, 'tools', 'dev-server.js');
  
  let serverPath;
  if (fs.existsSync(bundlerServerPath)) {
    // Check if esbuild is available
    try {
      require.resolve('esbuild');
      serverPath = bundlerServerPath;
      console.log('📦 Using bundler for full Angular compilation...\n');
    } catch (e) {
      console.log('⚠️  esbuild not found. Using simple static server.');
      console.log('   Install esbuild for full Angular support: npm install esbuild\n');
      serverPath = simpleServerPath;
    }
  } else if (fs.existsSync(simpleServerPath)) {
    serverPath = simpleServerPath;
  } else {
    console.error('Development server script not found.');
    process.exitCode = 1;
    return;
  }

  // Set PORT environment variable and start server
  const env = { ...process.env, PORT: port };
  const serverProcess = spawn('node', [serverPath], {
    cwd: workspaceRoot,
    env: env,
    stdio: 'inherit',
    shell: true
  });

  serverProcess.on('error', (error) => {
    console.error('Error starting server:', error.message);
    process.exitCode = 1;
  });

  serverProcess.on('exit', (code) => {
    if (code !== 0 && code !== null) {
      process.exitCode = code;
    }
  });
}

function buildProject(project, flags = []) {
  const { spawn } = require('child_process');
  const buildScriptPath = path.join(workspaceRoot, 'tools', 'build.js');
  
  if (!fs.existsSync(buildScriptPath)) {
    console.error('Build script not found.');
    process.exitCode = 1;
    return;
  }

  const flagSet = new Set(flags);
  const isProduction = flagSet.has('--configuration=production') || flagSet.has('--prod');
  
  console.log(`Building ${project}...`);
  console.log(`Mode: ${isProduction ? 'Production' : 'Development'}\n`);

  // Check if esbuild is available
  try {
    require.resolve('esbuild');
    console.log('📦 Using esbuild for compilation...\n');
  } catch (e) {
    console.error('❌ esbuild not found.');
    console.error('   Please install esbuild: npm install esbuild');
    console.error('   Or use: npm install --save-dev esbuild');
    process.exitCode = 1;
    return;
  }

  // Build arguments
  const buildArgs = [buildScriptPath];
  if (isProduction) {
    buildArgs.push('--prod');
  }

  // Execute build
  const buildProcess = spawn('node', buildArgs, {
    cwd: workspaceRoot,
    env: process.env,
    stdio: 'inherit',
    shell: true
  });

  buildProcess.on('error', (error) => {
    console.error('Error during build:', error.message);
    process.exitCode = 1;
  });

  buildProcess.on('exit', (code) => {
    if (code !== 0 && code !== null) {
      process.exitCode = code;
    }
  });
}

function showHelp() {
  console.log('Usage: nx <command> [project] [options]');
  console.log('Commands:');
  console.log('  graph        Displays a static project graph summary.');
  console.log('  test [proj]  Runs mock tests for a project or all projects.');
  console.log('               Pass --code-coverage to emit mock coverage artefacts.');
  console.log('  serve [proj] Starts a development server for the project.');
  console.log('               Options: --port <port>');
  console.log('  build [proj]  Builds the project.');
  console.log('               Options: --configuration=production, --prod');
}

function main() {
  const [, , ...argv] = process.argv;
  const { command, selection, flags } = parseCommandLine(argv);
  const nxConfig = loadNxConfig();
  const projects = nxConfig.projects || {};

  switch (command) {
    case 'graph':
      printGraph(projects);
      break;
    case 'test':
      runTests(projects, selection, flags);
      break;
    case 'serve':
      if (!selection) {
        console.error('Please specify a project to serve.');
        console.log('Available projects:', listProjects(projects).join(', '));
        process.exitCode = 1;
        return;
      }
      if (!projects[selection]) {
        console.error(`Unknown project '${selection}'.`);
        console.log('Available projects:', listProjects(projects).join(', '));
        process.exitCode = 1;
        return;
      }
      serveProject(selection, flags);
      break;
    case 'build':
      if (!selection) {
        console.error('Please specify a project to build.');
        console.log('Available projects:', listProjects(projects).join(', '));
        process.exitCode = 1;
        return;
      }
      if (!projects[selection]) {
        console.error(`Unknown project '${selection}'.`);
        console.log('Available projects:', listProjects(projects).join(', '));
        process.exitCode = 1;
        return;
      }
      buildProject(selection, flags);
      break;
    case undefined:
    case '--help':
    case '-h':
      showHelp();
      break;
    default:
      console.error(`Unknown command '${command}'.`);
      showHelp();
      process.exitCode = 1;
  }
}

main();
