export const ErrorCodes = {
    // General
    BAD_REQUEST: 'BAD_REQUEST',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

    // Auth
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    AUTH_REFRESH_TOKEN_NOT_FOUND: 'AUTH_REFRESH_TOKEN_NOT_FOUND',
    AUTH_USER_INACTIVE: 'AUTH_USER_INACTIVE',
    AUTH_USER_ALREADY_EXISTS: 'AUTH_USER_ALREADY_EXISTS',
    AUTH_REQUIRED: 'AUTH_REQUIRED',
    AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
    AUTH_PASSWORD_INCORRECT: 'AUTH_PASSWORD_INCORRECT',
    AUTH_PASSWORD_SAME: 'AUTH_PASSWORD_SAME',
    AUTH_OAUTH_FAILED: 'AUTH_OAUTH_FAILED',

    // Documents
    DOC_NOT_FOUND: 'DOC_NOT_FOUND',
    DOC_FILE_TOO_LARGE: 'DOC_FILE_TOO_LARGE',
    DOC_UNSUPPORTED_TYPE: 'DOC_UNSUPPORTED_TYPE',
    DOC_DUPLICATE: 'DOC_DUPLICATE',
    DOC_EXTRACTION_FAILED: 'DOC_EXTRACTION_FAILED',
    DOC_MISSING_FIELDS: 'DOC_MISSING_FIELDS',
    DOC_PROCESSING_FAILED: 'DOC_PROCESSING_FAILED',

    // Workspaces
    WS_NOT_FOUND: 'WS_NOT_FOUND',
    WS_ACCESS_DENIED: 'WS_ACCESS_DENIED',
    WS_QUOTA_EXCEEDED: 'WS_QUOTA_EXCEEDED',
    WS_NAME_CONFLICT: 'WS_NAME_CONFLICT',

    // Tasks
    TASK_NOT_FOUND: 'TASK_NOT_FOUND',
    TASK_ACCESS_DENIED: 'TASK_ACCESS_DENIED',
    TASK_ALREADY_COMPLETED: 'TASK_ALREADY_COMPLETED',
    TASK_FAILED: 'TASK_FAILED',

    // Q&A
    QNA_EMPTY_QUERY: 'QNA_EMPTY_QUERY',
    QNA_NO_DOCUMENTS: 'QNA_NO_DOCUMENTS',
    QNA_PROCESSING_FAILED: 'QNA_PROCESSING_FAILED',

    // Export
    EXPORT_NOT_FOUND: 'EXPORT_NOT_FOUND',
    EXPORT_FAILED: 'EXPORT_FAILED',

    // Share
    SHARE_NOT_FOUND: 'SHARE_NOT_FOUND',
    SHARE_EXPIRED: 'SHARE_EXPIRED',
    SHARE_ACCESS_DENIED: 'SHARE_ACCESS_DENIED',

    // Settings
    SETTINGS_UPDATE_FAILED: 'SETTINGS_UPDATE_FAILED',
    SETTINGS_INVALID_VALUE: 'SETTINGS_INVALID_VALUE',

    // System
    SYS_DATABASE_ERROR: 'SYS_DATABASE_ERROR',
    SYS_REDIS_ERROR: 'SYS_REDIS_ERROR',
    SYS_EXTERNAL_SERVICE_ERROR: 'SYS_EXTERNAL_SERVICE_ERROR',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

export interface ApiErrorResponse {
    code: string;      // Código constante para identificação e i18n
    message: string;   // Mensagem em inglês para desenvolvedores
    params?: {         // Parâmetros adicionais (opcional)
        [key: string]: any;
    };
}
